services:
  postgres:
    image: postgres:16
    container_name: weather-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: weather-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    depends_on:
      - postgres

  airflow-api-server:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: weather-airflow-api
    command: api-server

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hisoka:hisoka%40123@postgres:5432/airflow_db
    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    depends_on:
      - postgres

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: weather-airflow-scheduler

    command: scheduler

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hisoka:hisoka%40123@postgres:5432/airflow_db

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    depends_on:
      - postgres

  streamlit:
      build:
        context: .
        dockerfile: Dockerfile.streamlit
      container_name: weather-streamlit
      ports:
        - "8501:8501"
      depends_on:
        - postgres

volumes:
  postgres_data: